using System.Text.Json;
using CreativesIntegration.Api.Models;

namespace CreativesIntegration.Api.Data;

// Loads the committed tracking-events.json and rebases its dates onto the current
// 30-day window so the chart always has fresh data regardless of when the repo is run.
// The data is generated by the interviewer-only tools/TrackingDataGenerator project.
public static class TrackingEventLoader
{
    private const string FileName = "tracking-events.json";

    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    public static void Seed(AppDbContext dbContext)
    {
        var path = Path.Combine(AppContext.BaseDirectory, FileName);
        if (!File.Exists(path))
        {
            return;
        }

        var file = JsonSerializer.Deserialize<TrackingSeedFile>(File.ReadAllText(path), Options);
        if (file is null || file.Events.Count == 0)
        {
            return;
        }

        var shiftDays = DateOnly.FromDateTime(DateTime.UtcNow).DayNumber - file.AnchorDateUtc.DayNumber;

        foreach (var seedEvent in file.Events)
        {
            dbContext.TrackingEvents.Add(new TrackingEvent
            {
                Id = Guid.NewGuid(),
                CreativeId = seedEvent.CreativeId,
                EventType = seedEvent.EventType,
                ClientTimestampUtc = Shift(seedEvent.ClientTimestampUtc, shiftDays),
                ServerReceivedAtUtc = Shift(seedEvent.ServerReceivedAtUtc, shiftDays),
                InViewUtc = Shift(seedEvent.InViewUtc, shiftDays),
                OutOfViewUtc = Shift(seedEvent.OutOfViewUtc, shiftDays),
                SessionId = seedEvent.SessionId,
                UserAgent = seedEvent.UserAgent,
                DwellMs = seedEvent.DwellMs,
                Price = seedEvent.Price
            });
        }

        dbContext.SaveChanges();
    }

    private static DateTime Shift(DateTime value, int days) =>
        DateTime.SpecifyKind(value.AddDays(days), DateTimeKind.Utc);

    private static DateTime? Shift(DateTime? value, int days) =>
        value is null ? null : DateTime.SpecifyKind(value.Value.AddDays(days), DateTimeKind.Utc);

    private sealed class TrackingSeedFile
    {
        public DateOnly AnchorDateUtc { get; set; }

        public List<TrackingSeedEvent> Events { get; set; } = new();
    }

    private sealed class TrackingSeedEvent
    {
        public Guid CreativeId { get; set; }

        public string EventType { get; set; } = string.Empty;

        public DateTime ClientTimestampUtc { get; set; }

        public DateTime ServerReceivedAtUtc { get; set; }

        public DateTime? InViewUtc { get; set; }

        public DateTime? OutOfViewUtc { get; set; }

        public string SessionId { get; set; } = string.Empty;

        public string UserAgent { get; set; } = string.Empty;

        public int DwellMs { get; set; }

        public decimal Price { get; set; }
    }
}
